name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract version
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: sharedvolume/nfs-server
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}-alpine-3.22.0
          type=raw,value=latest
        labels: |
          org.opencontainers.image.title=Nfs Server
          org.opencontainers.image.description=A lightweight, production-ready NFS v4 server container based on Alpine Linux.
          org.opencontainers.image.version=${{ env.VERSION }}-alpine-3.22.0
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.licenses=Apache-2.0

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        generate_release_notes: true
        body: |
          ## Container Images Published

          The following container images have been built and pushed to Docker Hub:

          **Image:** `sharedvolume/nfs-server:${{ env.VERSION }}-alpine-3.22.0`
          
          **Tags:**
          ```
          ${{ steps.meta.outputs.tags }}
          ```
          
          **Supported Architectures:**
          - `linux/amd64`
          - `linux/arm64`